In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, datasets

In [9]:
x = tf.range(10)
print(x)
x = tf.random.shuffle(x)
print(x)
net = layers.Embedding(10, 4)
out = net(x)
print(out)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([2 0 1 9 6 3 7 4 8 5], shape=(10,), dtype=int32)
tf.Tensor(
[[-0.01543745 -0.0087777  -0.0446221  -0.03269279]
 [ 0.00245612  0.03518665 -0.01397281 -0.01812758]
 [-0.04655596  0.02843729  0.02555266  0.03509006]
 [-0.02314006  0.0335464  -0.00314863 -0.00068383]
 [-0.02387351 -0.01466048 -0.03196689  0.01343488]
 [-0.02637326 -0.01813256  0.01921226 -0.01290036]
 [-0.02818339  0.02377429 -0.04545987 -0.02338891]
 [ 0.03988026 -0.04180391  0.04833743 -0.03009104]
 [-0.00541577 -0.0136103  -0.00049096 -0.00729864]
 [ 0.00318483 -0.01020775 -0.02371028  0.04075596]], shape=(10, 4), dtype=float32)


global vectors for word representation

In [ ]:
embed_glove = datasets.load_embed('E:\TensorFlow_notes\source_code\glove.6B')